version: '3.3'
services:
  test-db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: 'pmodev'
      MYSQL_USER: 'kjlee'
      MYSQL_PASSWORD: '1234'
      MYSQL_ROOT_PASSWORD: '1234'
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - my-db:/var/lib/mysql

  test_app:
    image: illylee/docker-boot-app
    volumes:
      - ./docker-app:/docker-app
    ports:
      - 8001:8080
    depends_on:
      - test-db

# Names our volume
volumes:
  my-db:
